export declare const PACK_LAYOUT: any;
export declare const LEARNING_SPINE_LOG_LAYOUT: any;
export declare function computePayloadChecksum(value: any): string;
export declare function writePackFile(rootDir: string, relativePath: string, value: any): string;
export declare function loadPack(rootDir: string): any;
export declare function loadActivationPointers(activationRoot: string): any;
export declare function loadPackFromActivation(activationRoot: string, slot: string, options?: any): any;
export declare function inspectActivationState(activationRoot: string): any;
export declare function describeActivationTarget(activationRoot: string, slot: string): any;
export declare function describeActivationObservability(activationRoot: string, slot: string): any;
export declare function describePackCompileTarget(target: any): any;
export declare function stageCandidatePack(activationRoot: string, candidatePackRoot: string, options?: any): any;
export declare function promoteCandidatePack(activationRoot: string, options?: any): any;
export declare function rollbackActivePack(activationRoot: string, options?: any): any;
export declare function activatePack(activationRoot: string, candidatePackRoot: string, options?: any): any;
export declare function resolveLearningSpineLogPath(activationRoot: string, kind: string): string;
export declare function appendLearningSpineLogEntry(activationRoot: string, kind: string, entry: any): string;
export declare function readLearningSpineLogEntries(activationRoot: string, kind: string): any[];
export declare function buildLearningSpineLogId(prefix: string, value: any): string;
export declare function summarizeStructuralGraphEvolution(graph: any): any;
export type PackDescriptor = any;
export type GraphEvolutionLogV1 = any;
export type LearningSpineServeRouteDecisionLogEntryV1 = any;
export type LearningSpinePgRouteUpdateLogEntryV1 = any;
export type LearningSpineServeRouteBreadcrumbsV1 = any;
export type ActivationInspection = any;
export type ActivationObservabilityReport = any;
export type ActivationSlotInspection = any;
export type InitHandoffState = any;
