import { spawnSync } from 'node:child_process';
import { fileURLToPath } from 'node:url';
import path from 'node:path';
import { defaultActivationRoot, writeStatus } from '../../proof-store/src/index.mjs';
const repoRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..', '..', '..');
export function buildOpenClawBrainConfigPatch({ profile = 'main', mode = 'conservative', activationRoot = defaultActivationRoot(profile), agents = [profile] } = {}) { return { plugins: { entries: { openclawbrain: { enabled: true, hooks: { allowPromptInjection: true, allowConversationAccess: true }, config: { enabled: true, mode, activationRoot, proofEvents: true, rawTranscriptUpload: false, scopes: { agents } } } } } }; }
export async function initializeProfileActivation({ profile = 'main', mode = 'conservative', activationRoot = defaultActivationRoot(profile), enabled = true } = {}) { return writeStatus({ profileId: profile, enabled, mode, runtimeAdapter: enabled ? 'configured' : 'disabled', proofEvents: enabled ? 'ready' : 'not-writing', rawTranscriptUpload: 'disabled', profileIsolation: 'pass', lastDecision: 'none', lastDecisionAt: null }, { profileId: profile, activationRoot }); }
export function runOpenClawCommand(args, { dryRun = false, cwd = repoRoot } = {}) { if (dryRun) return { ok: true, dryRun: true, command: ['openclaw', ...args].join(' ') }; const result = spawnSync('openclaw', args, { cwd, encoding: 'utf8' }); return { ok: result.status === 0, status: result.status, stdout: result.stdout, stderr: result.stderr, command: ['openclaw', ...args].join(' ') }; }
export async function installOpenClawBrain({ dryRun = false, source = repoRoot } = {}) { return runOpenClawCommand(['plugins', 'install', source], { dryRun }); }
export async function enableOpenClawBrain({ profile = 'main', mode = 'conservative', dryRun = false, activationRoot = defaultActivationRoot(profile) } = {}) { await initializeProfileActivation({ profile, mode, activationRoot, enabled: true }); const commands = [['plugins', 'enable', 'openclawbrain'], ['config', 'set', 'plugins.entries.openclawbrain.enabled', 'true'], ['config', 'set', 'plugins.entries.openclawbrain.hooks.allowPromptInjection', 'true'], ['config', 'set', 'plugins.entries.openclawbrain.hooks.allowConversationAccess', 'true'], ['config', 'set', 'plugins.entries.openclawbrain.config.enabled', 'true'], ['config', 'set', 'plugins.entries.openclawbrain.config.mode', mode], ['config', 'set', 'plugins.entries.openclawbrain.config.activationRoot', activationRoot], ['config', 'set', 'plugins.entries.openclawbrain.config.proofEvents', 'true'], ['config', 'set', 'plugins.entries.openclawbrain.config.rawTranscriptUpload', 'false']]; return commands.map((args) => runOpenClawCommand(args, { dryRun })); }
export async function disableOpenClawBrain({ profile = 'main', dryRun = false, activationRoot = defaultActivationRoot(profile) } = {}) { await initializeProfileActivation({ profile, activationRoot, enabled: false }); return [runOpenClawCommand(['config', 'set', 'plugins.entries.openclawbrain.config.enabled', 'false'], { dryRun }), runOpenClawCommand(['plugins', 'disable', 'openclawbrain'], { dryRun })]; }
