import { spawnSync } from 'node:child_process';
import { defaultActivationRoot, writeStatus } from '../../proof-store/src/index.mjs';
export function buildOpenClawBrainConfigPatch({ profile = 'main', mode = 'conservative', activationRoot = defaultActivationRoot(profile), agents = [profile], sessionKeys = [] } = {}) { return { plugins: { entries: { openclawbrain: { enabled: true, hooks: { allowPromptInjection: true, allowConversationAccess: true }, config: { enabled: true, mode, openclawProfile: profile, activationRoot, proofEvents: true, rawTranscriptUpload: false, scopes: { agents, sessionKeys } } } } } }; }
export async function initializeProfileActivation({ profile = 'main', mode = 'conservative', activationRoot = defaultActivationRoot(profile), enabled = true, agentId = profile, sessionKeyHash = null } = {}) { return writeStatus({ profileId: profile, openclawProfile: profile, agentId, sessionKeyHash, enabled, mode, runtimeAdapter: enabled ? 'configured' : 'disabled', proofEvents: enabled ? 'ready' : 'not-writing', rawTranscriptUpload: 'disabled', profileIsolation: 'pass', lastDecision: 'none', lastDecisionAt: null }, { profileId: profile, activationRoot }); }
export function runOpenClawCommand(args, { dryRun = false, cwd = process.cwd() } = {}) { if (dryRun) return { ok: true, dryRun: true, command: ['openclaw', ...args].join(' ') }; const result = spawnSync('openclaw', args, { cwd, encoding: 'utf8' }); return { ok: result.status === 0, status: result.status, stdout: result.stdout, stderr: result.stderr, command: ['openclaw', ...args].join(' ') }; }
export async function installOpenClawBrain({ dryRun = false, source = 'openclawbrain', link = false } = {}) { const args = ['plugins', 'install']; if (link) args.push('-l'); args.push(source); return runOpenClawCommand(args, { dryRun }); }
export async function inspectOpenClawBrain({ dryRun = false } = {}) { return runOpenClawCommand(['plugins', 'inspect', 'openclawbrain', '--json'], { dryRun }); }
export async function enableOpenClawBrain({ profile = 'main', mode = 'conservative', dryRun = false, activationRoot = defaultActivationRoot(profile), agents = [profile], sessionKeys = [], restart = true } = {}) { await initializeProfileActivation({ profile, mode, activationRoot, enabled: true, agentId: agents[0] ?? profile }); const commands = [['plugins', 'enable', 'openclawbrain'], ['config', 'set', 'plugins.entries.openclawbrain.enabled', 'true', '--strict-json'], ['config', 'set', 'plugins.entries.openclawbrain.hooks.allowPromptInjection', 'true', '--strict-json'], ['config', 'set', 'plugins.entries.openclawbrain.hooks.allowConversationAccess', 'true', '--strict-json'], ['config', 'set', 'plugins.entries.openclawbrain.config.enabled', 'true', '--strict-json'], ['config', 'set', 'plugins.entries.openclawbrain.config.mode', mode], ['config', 'set', 'plugins.entries.openclawbrain.config.openclawProfile', profile], ['config', 'set', 'plugins.entries.openclawbrain.config.activationRoot', activationRoot], ['config', 'set', 'plugins.entries.openclawbrain.config.proofEvents', 'true', '--strict-json'], ['config', 'set', 'plugins.entries.openclawbrain.config.rawTranscriptUpload', 'false', '--strict-json'], ['config', 'set', 'plugins.entries.openclawbrain.config.scopes', JSON.stringify({ agents, sessionKeys }), '--strict-json']]; if (restart) commands.push(['gateway', 'restart']); return commands.map((args) => runOpenClawCommand(args, { dryRun })); }
export async function disableOpenClawBrain({ profile = 'main', dryRun = false, activationRoot = defaultActivationRoot(profile), restart = true } = {}) { await initializeProfileActivation({ profile, activationRoot, enabled: false }); const commands = [['config', 'set', 'plugins.entries.openclawbrain.config.enabled', 'false', '--strict-json'], ['plugins', 'disable', 'openclawbrain']]; if (restart) commands.push(['gateway', 'restart']); return commands.map((args) => runOpenClawCommand(args, { dryRun })); }
