import { decideOpenClawBrainIntervention } from '../../runtime-policy/src/index.mjs';
import { appendProofEvent, writeStatus } from '../../proof-store/src/index.mjs';
const DEFAULT_CONFIG = Object.freeze({ enabled: true, mode: 'conservative', activationRoot: '~/.openclawbrain/activation/main', proofEvents: true, rawTranscriptUpload: false, scopes: { agents: ['main'] }, candidateMemories: [] });
export const openClawBrainPluginEntry = { id: 'openclawbrain', name: 'OpenClawBrain', register(api) { const resolve = () => resolveOpenClawBrainConfig(api); api.on?.('before_prompt_build', async (event = {}) => { const config = resolve(); if (!config.enabled || config.mode === 'off' || config.rawTranscriptUpload !== false) return {}; const redactedTurn = redactedTurnFromPromptEvent(event, config); if (!agentAllowed(redactedTurn.agentId, config)) return {}; const decision = decideOpenClawBrainIntervention({ profileId: profileIdFromConfig(config, redactedTurn.agentId), redactedTurn, candidateMemories: config.candidateMemories, toolContext: toolContextFromPromptEvent(event), runtimeMode: config.mode }); await maybeWriteProof(decision.proof, config, api); if (decision.kind === 'correction_only') return { prependSystemContext: wrapInjectedContext(decision.message) }; if (decision.kind === 'full_context') return { prependSystemContext: wrapInjectedContext(decision.context) }; return {}; }); api.on?.('agent_end', async (event = {}) => { const config = resolve(); if (!config.proofEvents) return; await writeStatus({ profileId: profileIdFromConfig(config, agentIdFromEvent(event)), enabled: config.enabled, mode: config.mode, runtimeAdapter: 'connected', proofEvents: 'writing', rawTranscriptUpload: 'disabled', profileIsolation: 'pass', lastDecision: 'observed_agent_end', lastDecisionAt: new Date().toISOString() }, { activationRoot: config.activationRoot, profileId: profileIdFromConfig(config, agentIdFromEvent(event)) }); }); } };
export default openClawBrainPluginEntry;
export function resolveOpenClawBrainConfig(api = {}) { const pluginConfig = livePluginConfig(api) ?? ((api.pluginConfig && typeof api.pluginConfig === 'object') ? api.pluginConfig : {}); return normalizePluginConfig({ ...DEFAULT_CONFIG, ...pluginConfig }); }
function livePluginConfig(api) { try { const loaded = api.runtime?.config?.loadConfig?.(); const config = loaded?.plugins?.entries?.openclawbrain?.config; return config && typeof config === 'object' && !Array.isArray(config) ? config : null; } catch { return null; } }
export function normalizePluginConfig(config) { const mode = ['off', 'proof-only', 'conservative', 'active'].includes(config.mode) ? config.mode : 'conservative'; return { enabled: config.enabled !== false, mode, activationRoot: typeof config.activationRoot === 'string' && config.activationRoot.trim() ? config.activationRoot.trim() : DEFAULT_CONFIG.activationRoot, proofEvents: config.proofEvents !== false, rawTranscriptUpload: false, scopes: normalizeScopes(config.scopes), candidateMemories: Array.isArray(config.candidateMemories) ? config.candidateMemories : [] }; }
export function redactedTurnFromPromptEvent(event = {}, config = DEFAULT_CONFIG) { const agentId = agentIdFromEvent(event); const latest = latestUserTextRedacted(event); return { turnId: safeString(event.turnId ?? event.turn_id ?? event.requestId ?? event.request_id ?? 'turn-redacted'), turnType: safeString(event.turnType ?? event.turn_type ?? ''), summary: latest, channel: safeString(event.channel ?? event.surface ?? 'openclaw'), agentId, profileId: profileIdFromConfig(config, agentId) }; }
function wrapInjectedContext(text) { return `<openclawbrain_context>\n${text}\n\nPrivacy: local redacted context only; raw transcripts were not uploaded.\n</openclawbrain_context>`; }
async function maybeWriteProof(proof, config, api) { if (!config.proofEvents) return; try { await appendProofEvent(proof, { activationRoot: config.activationRoot, profileId: proof.profile_id, enabled: config.enabled, mode: config.mode, runtimeAdapter: 'connected' }); } catch (error) { api.logger?.warn?.({ error }, 'OpenClawBrain failed to write proof event'); } }
function latestUserTextRedacted(event) { if (typeof event.userMessageRedacted === 'string') return event.userMessageRedacted; if (typeof event.user_message_redacted === 'string') return event.user_message_redacted; if (typeof event.input === 'string') return truncate(event.input); if (Array.isArray(event.messages)) { const latest = [...event.messages].reverse().find((message) => message?.role === 'user'); if (typeof latest?.redactedText === 'string') return latest.redactedText; if (typeof latest?.content === 'string') return truncate(latest.content); } return safeString(event.summary ?? 'redacted OpenClaw turn'); }
function toolContextFromPromptEvent(event) { if (event.toolContext && typeof event.toolContext === 'object') return event.toolContext; return { summary: event.tools?.length ? `Available tools: ${event.tools.length}` : '', readOnlyPreferred: true }; }
function agentAllowed(agentId, config) { const agents = config.scopes?.agents ?? []; return agents.length === 0 || agents.includes(agentId); }
function profileIdFromConfig(config, fallback) { const match = String(config.activationRoot ?? '').match(/activation\/([^/]+)\/?$/); return match?.[1] || fallback || 'main'; }
function agentIdFromEvent(event = {}) { return safeString(event.agentId ?? event.agent_id ?? event.profileId ?? event.profile_id ?? event.session?.agentId ?? 'main'); }
function normalizeScopes(scopes) { const agents = Array.isArray(scopes?.agents) ? scopes.agents.map(safeString).filter(Boolean) : ['main']; return { agents }; }
function truncate(text, max = 500) { const safe = safeString(text); return safe.length > max ? `${safe.slice(0, max)}…` : safe; }
function safeString(value) { return typeof value === 'string' ? value.trim() : String(value ?? '').trim(); }
