import { decideOpenClawBrainIntervention, hashScopeValue } from '../../runtime-policy/src/index.mjs';
import { appendProofEvent, readStatus, writeStatus } from '../../proof-store/src/index.mjs';
const DEFAULT_CONFIG = Object.freeze({ enabled: true, mode: 'conservative', openclawProfile: 'main', activationRoot: '~/.openclawbrain/activation/main', proofEvents: true, rawTranscriptUpload: false, scopes: { agents: ['main'], sessionKeys: [] }, candidateMemories: [], hooks: { allowPromptInjection: true, allowConversationAccess: false } });
export const openClawBrainPluginEntry = { id: 'openclawbrain', name: 'OpenClawBrain', register(api) { const resolve = () => resolveOpenClawBrainConfig(api); registerFirstClassSurfaces(api, resolve); registerTurnHooks(api, resolve); api.on?.('model_call_started', async (event = {}) => { await writeLifecycleStatus('model_call_started', event, resolve(), api); }); api.on?.('model_call_ended', async (event = {}) => { await writeLifecycleStatus('model_call_ended', event, resolve(), api); }); api.on?.('agent_end', async (event = {}) => { await writeLifecycleStatus('agent_end', event, resolve(), api); }); api.on?.('gateway_start', async (event = {}) => { await writeLifecycleStatus('gateway_start', event, resolve(), api); }); api.on?.('gateway_stop', async (event = {}) => { await writeLifecycleStatus('gateway_stop', event, resolve(), api); }); } };
export default openClawBrainPluginEntry;
export function resolveOpenClawBrainConfig(api = {}) { const entry = livePluginEntry(api); const pluginConfig = entry?.config ?? ((api.pluginConfig && typeof api.pluginConfig === 'object') ? api.pluginConfig : {}); return normalizePluginConfig({ ...DEFAULT_CONFIG, ...pluginConfig, hooks: entry?.hooks ?? pluginConfig.hooks }); }
function livePluginEntry(api) { try { const entry = api.runtime?.config?.loadConfig?.()?.plugins?.entries?.openclawbrain; return entry && typeof entry === 'object' && !Array.isArray(entry) ? entry : null; } catch { return null; } }
export function normalizePluginConfig(config) { const mode = ['off', 'proof-only', 'conservative', 'active'].includes(config.mode) ? config.mode : 'conservative'; return { enabled: config.enabled !== false, mode, openclawProfile: safeString(config.openclawProfile ?? config.profile ?? DEFAULT_CONFIG.openclawProfile), activationRoot: typeof config.activationRoot === 'string' && config.activationRoot.trim() ? config.activationRoot.trim() : DEFAULT_CONFIG.activationRoot, proofEvents: config.proofEvents !== false, rawTranscriptUpload: false, scopes: normalizeScopes(config.scopes), candidateMemories: Array.isArray(config.candidateMemories) ? config.candidateMemories : [], hooks: { allowPromptInjection: config.hooks?.allowPromptInjection !== false, allowConversationAccess: config.hooks?.allowConversationAccess === true } }; }
export function redactedTurnFromPromptEvent(event = {}, config = DEFAULT_CONFIG) { const ctx = event.ctx ?? {}; const agentId = agentIdFromEvent(event); const latest = latestUserTextRedacted(event); const scope = scopeFromEvent(event, config, agentId); return { turnId: safeString(event.turnId ?? event.turn_id ?? event.requestId ?? event.request_id ?? ctx.runId ?? 'turn-redacted'), turnType: safeString(event.turnType ?? event.turn_type ?? ''), summary: latest, channel: safeString(event.channel ?? event.surface ?? 'openclaw'), agentId, profileId: profileIdFromConfig(config, agentId), openclawProfile: scope.openclawProfile, sessionKeyHash: scope.sessionKeyHash, sessionIdHash: scope.sessionIdHash, runIdHash: scope.runIdHash }; }
function registerTurnHooks(api, resolve) { const handler = (phase) => async (event = {}) => handleTurnHook(event, resolve(), api, phase); tryRegisterHook(api, 'agent_turn_prepare', handler('agent_turn_prepare')); tryRegisterHook(api, 'before_prompt_build', handler('before_prompt_build')); }
async function handleTurnHook(event, config, api, phase) { if (!config.enabled || config.mode === 'off' || config.rawTranscriptUpload !== false) return {}; const redactedTurn = redactedTurnFromPromptEvent(event, config); if (!scopeAllowed(redactedTurn, config, event)) return {}; const input = { profileId: profileIdFromConfig(config, redactedTurn.agentId), openclawProfile: redactedTurn.openclawProfile, agentId: redactedTurn.agentId, sessionKeyHash: redactedTurn.sessionKeyHash, sessionIdHash: redactedTurn.sessionIdHash, runIdHash: redactedTurn.runIdHash, redactedTurn, candidateMemories: config.candidateMemories, toolContext: toolContextFromPromptEvent(event), runtimeMode: config.mode }; const decision = decideOpenClawBrainIntervention(input); if (!config.hooks.allowPromptInjection && decision.kind !== 'stay_silent' && decision.kind !== 'proof_only') { const proof = { ...decision.proof, decision: 'stay_silent', decisionKind: 'stay_silent', reason: 'prompt injection disabled by plugins.entries.openclawbrain.hooks.allowPromptInjection=false', reason_code: 'prompt_injection_disabled' }; await maybeWriteProof(proof, config, api); return {}; } await maybeWriteProof({ ...decision.proof, hook_phase: phase }, config, api); if (decision.kind === 'proof_only' || decision.kind === 'stay_silent') return {}; if (shouldQueueNextTurn(event) && typeof api.enqueueNextTurnInjection === 'function') { api.enqueueNextTurnInjection({ pluginId: 'openclawbrain', agentId: redactedTurn.agentId, sessionKeyHash: redactedTurn.sessionKeyHash, context: injectedText(decision), once: true }); return {}; } return decision.kind === 'correction_only' ? { prependContext: wrapInjectedContext(decision.message) } : { appendContext: wrapInjectedContext(decision.context) }; }
function registerFirstClassSurfaces(api, resolve) { api.registerHttpRoute?.({ path: '/plugins/openclawbrain/status', auth: 'gateway', match: 'exact', replaceExisting: true, handler: async (_req, res) => { const config = resolve(); const profileId = profileIdFromConfig(config, config.scopes.agents[0] ?? 'main'); const status = await readStatus({ activationRoot: config.activationRoot, profileId }); res.statusCode = 200; res.setHeader?.('content-type', 'application/json'); res.end(JSON.stringify({ ok: true, plugin: 'openclawbrain', config: { enabled: config.enabled, mode: config.mode, rawTranscriptUpload: false }, status })); return true; } }); api.registerGatewayMethod?.('openclawbrain.status', async () => { const config = resolve(); const profileId = profileIdFromConfig(config, config.scopes.agents[0] ?? 'main'); return readStatus({ activationRoot: config.activationRoot, profileId }); }); }
async function writeLifecycleStatus(marker, event, config, api) { if (!config.proofEvents) return; const agentId = agentIdFromEvent(event); const scope = scopeFromEvent(event, config, agentId); try { await writeStatus({ profileId: profileIdFromConfig(config, agentId), openclawProfile: scope.openclawProfile, agentId, sessionKeyHash: scope.sessionKeyHash, enabled: config.enabled, mode: config.mode, runtimeAdapter: 'connected', proofEvents: 'writing', rawTranscriptUpload: 'disabled', profileIsolation: 'pass', lastDecision: marker, lastDecisionAt: new Date().toISOString() }, { activationRoot: config.activationRoot, profileId: profileIdFromConfig(config, agentId) }); } catch (error) { api.logger?.warn?.({ error }, 'OpenClawBrain failed to write lifecycle status'); } }
function wrapInjectedContext(text) { return `<openclawbrain_context>\n${text}\n\nPrivacy: local redacted context only; raw transcripts were not uploaded.\n</openclawbrain_context>`; }
function injectedText(decision) { return decision.kind === 'correction_only' ? decision.message : decision.context; }
async function maybeWriteProof(proof, config, api) { if (!config.proofEvents) return; try { await appendProofEvent(proof, { activationRoot: config.activationRoot, profileId: proof.profile_id, enabled: config.enabled, mode: config.mode, runtimeAdapter: 'connected' }); } catch (error) { api.logger?.warn?.({ error }, 'OpenClawBrain failed to write proof event'); } }
function latestUserTextRedacted(event) { if (typeof event.userMessageRedacted === 'string') return event.userMessageRedacted; if (typeof event.user_message_redacted === 'string') return event.user_message_redacted; if (typeof event.input === 'string') return truncate(event.input); if (Array.isArray(event.messages)) { const latest = [...event.messages].reverse().find((message) => message?.role === 'user'); if (typeof latest?.redactedText === 'string') return latest.redactedText; if (typeof latest?.content === 'string') return truncate(latest.content); } return safeString(event.summary ?? 'redacted OpenClaw turn'); }
function toolContextFromPromptEvent(event) { if (event.toolContext && typeof event.toolContext === 'object') return event.toolContext; return { summary: event.tools?.length ? `Available tools: ${event.tools.length}` : '', readOnlyPreferred: true }; }
function scopeAllowed(redactedTurn, config, event) { const agents = config.scopes?.agents ?? []; if (agents.length > 0 && !agents.includes(redactedTurn.agentId)) return false; const sessionKeys = config.scopes?.sessionKeys ?? []; if (sessionKeys.length === 0) return true; const sessionKey = event.ctx?.sessionKey ?? event.sessionKey ?? event.session_key; return sessionKeys.map(hashScopeValue).includes(redactedTurn.sessionKeyHash) || sessionKeys.includes(sessionKey); }
function profileIdFromConfig(config, fallback) { const match = String(config.activationRoot ?? '').match(/activation\/([^/]+)\/?$/); return match?.[1] || config.openclawProfile || fallback || 'main'; }
function agentIdFromEvent(event = {}) { return safeString(event.ctx?.agentId ?? event.agentId ?? event.agent_id ?? event.profileId ?? event.profile_id ?? event.session?.agentId ?? 'main'); }
function scopeFromEvent(event = {}, config = DEFAULT_CONFIG, agentId = 'main') { const ctx = event.ctx ?? {}; return { openclawProfile: safeString(ctx.openclawProfile ?? ctx.profile ?? event.openclawProfile ?? event.profile ?? config.openclawProfile ?? profileIdFromConfig(config, agentId)), agentId, sessionKeyHash: safeString(event.sessionKeyHash ?? ctx.sessionKeyHash ?? hashScopeValue(ctx.sessionKey ?? event.sessionKey ?? event.session_key)), sessionIdHash: safeString(event.sessionIdHash ?? ctx.sessionIdHash ?? hashScopeValue(ctx.sessionId ?? event.sessionId ?? event.session_id)), runIdHash: safeString(event.runIdHash ?? ctx.runIdHash ?? hashScopeValue(ctx.runId ?? event.runId ?? event.run_id)) }; }
function normalizeScopes(scopes) { const agents = Array.isArray(scopes?.agents) ? scopes.agents.map(safeString).filter(Boolean) : ['main']; const sessionKeys = Array.isArray(scopes?.sessionKeys) ? scopes.sessionKeys.map(safeString).filter(Boolean) : []; return { agents, sessionKeys }; }
function shouldQueueNextTurn(event) { return event.queueNextTurn === true || event.enqueueNextTurn === true || event.nextTurn === true; }
function tryRegisterHook(api, name, fn) { try { api.on?.(name, fn); } catch (error) { api.logger?.debug?.({ hook: name, error }, 'OpenClawBrain hook unavailable; skipping'); } }
function truncate(text, max = 500) { const safe = safeString(text); return safe.length > max ? `${safe.slice(0, max)}…` : safe; }
function safeString(value) { return typeof value === 'string' ? value.trim() : String(value ?? '').trim(); }
