#!/usr/bin/env node
import { realpathSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { renderProof, renderStatus, defaultActivationRoot } from '../../proof-store/src/index.mjs';
import { disableOpenClawBrain, enableOpenClawBrain, initializeProfileActivation, installOpenClawBrain } from '../../installer/src/index.mjs';
export async function main(argv = process.argv.slice(2), io = console) { const { command, options } = parseArgs(argv); const profile = options.profile ?? 'main'; const activationRoot = options.activationRoot ?? defaultActivationRoot(profile); const dryRun = options.dryRun === true; if (!command || options.help) return io.log(help()); if (command === 'install') { const result = await installOpenClawBrain({ dryRun, source: options.source }); if (!result.ok) throw new Error(result.stderr || `${result.command} failed`); io.log(dryRun ? `DRY RUN: ${result.command}` : 'OpenClawBrain plugin installed. Restart the OpenClaw Gateway if it is already running.'); return; } if (command === 'enable') { const results = await enableOpenClawBrain({ profile, mode: options.mode ?? 'conservative', activationRoot, dryRun }); const failed = results.find((result) => !result.ok); if (failed) throw new Error(failed.stderr || `${failed.command} failed`); io.log(`OpenClawBrain enabled for profile: ${profile}\nMode: ${options.mode ?? 'conservative'}\nRaw transcript upload: disabled\nConfig path: plugins.entries.openclawbrain.config`); return; } if (command === 'disable') { const results = await disableOpenClawBrain({ profile, activationRoot, dryRun }); const failed = results.find((result) => !result.ok); if (failed) throw new Error(failed.stderr || `${failed.command} failed`); io.log(`OpenClawBrain disabled for profile: ${profile}`); return; } if (command === 'status') return io.log(await renderStatus({ profileId: profile, activationRoot })); if (command === 'proof') return io.log(await renderProof({ profileId: profile, activationRoot, limit: options.limit })); if (command === 'doctor') return io.log(await doctor({ profile, activationRoot })); if (command === 'uninstall') { await initializeProfileActivation({ profile, activationRoot, enabled: false }); io.log(`OpenClawBrain profile state disabled for: ${profile}\nTo remove plugin files, run: openclaw plugins uninstall openclawbrain`); return; } throw new Error(`Unknown command: ${command}`); }
export function parseArgs(argv) { const [command, ...rest] = argv; const options = {}; for (let i = 0; i < rest.length; i += 1) { const arg = rest[i]; if (arg === '--profile') options.profile = rest[++i]; else if (arg === '--mode') options.mode = rest[++i]; else if (arg === '--activation-root') options.activationRoot = rest[++i]; else if (arg === '--source') options.source = rest[++i]; else if (arg === '--limit') options.limit = Number(rest[++i]); else if (arg === '--dry-run') options.dryRun = true; else if (arg === '--help' || arg === '-h') options.help = true; else throw new Error(`Unknown argument: ${arg}`); } return { command, options }; }
async function doctor({ profile, activationRoot }) { return ['OpenClawBrain doctor', '', `Profile: ${profile}`, `Activation root: ${activationRoot}`, 'Config shape: plugins.entries.openclawbrain.config', 'Raw transcript upload: disabled', 'Profile isolation: local activation root per profile', 'Gateway note: plugin install/config changes require an OpenClaw Gateway restart.'].join('\n'); }
function help() { return `Usage: openclawbrain <command> [options]\n\nCommands:\n  install\n  enable --profile <profile> [--mode conservative]\n  disable --profile <profile>\n  status --profile <profile>\n  proof --profile <profile>\n  doctor\n  uninstall --profile <profile>\n\nSafety defaults: conservative mode, profile-local proof events, raw transcript upload disabled.`; }
function isDirectRun() { try { return process.argv[1] && realpathSync(process.argv[1]) === fileURLToPath(import.meta.url); } catch { return false; } }
if (isDirectRun()) { main().catch((error) => { console.error(error instanceof Error ? error.message : String(error)); process.exitCode = 1; }); }
