export declare function canonicalJson(value: unknown): string;
export declare function checksumJsonPayload(value: unknown): string;
export declare const CONTRACT_IDS: {
  interactionEvents: string;
  feedbackEvents: string;
  normalizedEventExport: string;
  kernelSurface: string;
  normalizedKernelEventExport: string;
  runtimeCompile: string;
  runtimeCompileRequest: string;
  teacherSupervisionArtifact: string;
  routerArtifact: string;
};
export declare function createInteractionEvent(input: any): any;
export declare function createFeedbackEvent(input: any): any;
export declare function sortNormalizedEvents(events: any[]): any[];
export declare function buildNormalizedEventExport(input?: { interactionEvents?: any[]; feedbackEvents?: any[] }): any;
export declare function buildEventSemanticSurface(value: any): any;
export declare function validateKernelSurface(...args: any[]): any;
export declare function validateNormalizedEventExport(...args: any[]): any;
export declare function validateRuntimeCompileRequest(...args: any[]): any;
export declare function buildRouteArtifactReference(value: any): any;
export declare const PACK_GRAPH_SCHEMAS: any;
export declare const ROUTER_PG_PROFILE_V1: string;
export declare const ROUTER_PG_PROFILE_V2: string;
export declare function validateTeacherSupervisionArtifact(...args: any[]): any;
export declare function computeRouterCollectedLabelCounts(...args: any[]): any;
export declare function computeRouterFreshnessChecksum(...args: any[]): any;
export declare function computeRouterObjectiveChecksum(...args: any[]): any;
export declare function computeRouterQueryChecksum(...args: any[]): any;
export declare function computeRouterWeightsChecksum(...args: any[]): any;
