export const HARD_MEMORY_SCORECARD_CONTRACT: any;
export const HARD_MEMORY_SCORECARD_JSON_FILE: any;
export const HARD_MEMORY_SCORECARD_MARKDOWN_FILE: any;
export const HARD_MEMORY_LABEL_SCHEMA: any;
export const isStrictHardMemoryLabelRecord: any;
export const buildHardMemoryScorecard: any;
export const buildHardMemoryScorecardMarkdown: any;
export const writeHardMemoryScorecardOutputs: any;
export const main: any;
