import assert from 'node:assert/strict';
import { mkdtemp, readFile, rm } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import path from 'node:path';
import test from 'node:test';
import plugin, { normalizePluginConfig, redactedTurnFromPromptEvent, resolveOpenClawBrainConfig } from '../src/index.mjs';

test('plugin registers prompt, lifecycle, and first-class HTTP surfaces', () => { const calls = []; const routes = []; plugin.register({ pluginConfig: {}, on: (name, fn) => calls.push([name, fn]), registerHttpRoute: (route) => routes.push(route) }); assert.ok(calls.map(([name]) => name).includes('before_prompt_build')); assert.ok(calls.map(([name]) => name).includes('agent_turn_prepare')); assert.ok(calls.map(([name]) => name).includes('model_call_started')); assert.ok(calls.map(([name]) => name).includes('gateway_start')); assert.equal(routes[0].path, '/plugins/openclawbrain/status'); });

test('before_prompt_build injects correction and writes scoped proof under activation root', async () => { const root = await mkdtemp(path.join(tmpdir(), 'ocb-plugin-')); try { const hooks = {}; plugin.register({ pluginConfig: { enabled: true, mode: 'conservative', openclawProfile: 'ExampleProfile', activationRoot: root, scopes: { agents: ['main'] }, candidateMemories: [{ id: 'correction-redacted', kind: 'correction', text: 'avoid work email for family tasks', relevance: 1 }] }, on: (name, fn) => { hooks[name] = fn; }, logger: { warn() {}, debug() {} } }); const result = await hooks.before_prompt_build({ ctx: { agentId: 'main', sessionKey: 'session-redacted', runId: 'run-redacted' }, turnId: 't1', turnType: 'stale-memory-conflict', userMessageRedacted: 'ambiguous family email request' }); assert.match(result.prependContext, /Relevant user correction/); const proof = await readFile(path.join(root, 'proof-events.jsonl'), 'utf8'); assert.match(proof, /correction_only/); assert.match(proof, /session_key_hash/); assert.doesNotMatch(proof, /session-redacted/); } finally { await rm(root, { recursive: true, force: true }); } });

test('before_prompt_build fails closed when prompt injection is disabled', async () => { const root = await mkdtemp(path.join(tmpdir(), 'ocb-plugin-')); try { const hooks = {}; plugin.register({ pluginConfig: { hooks: { allowPromptInjection: false }, activationRoot: root, scopes: { agents: ['main'] }, candidateMemories: [{ id: 'correction-redacted', kind: 'correction', text: 'avoid work email', relevance: 1 }] }, on: (name, fn) => { hooks[name] = fn; }, logger: { warn() {}, debug() {} } }); const result = await hooks.before_prompt_build({ agentId: 'main', turnType: 'stale-memory-conflict', userMessageRedacted: 'ambiguous email request' }); assert.deepEqual(result, {}); const proof = await readFile(path.join(root, 'proof-events.jsonl'), 'utf8'); assert.match(proof, /prompt_injection_disabled/); assert.match(proof, /stay_silent/); } finally { await rm(root, { recursive: true, force: true }); } });

test('before_prompt_build stays silent when scoped agent does not match', async () => { const hooks = {}; plugin.register({ pluginConfig: { scopes: { agents: ['family'] } }, on: (name, fn) => { hooks[name] = fn; } }); assert.deepEqual(await hooks.before_prompt_build({ agentId: 'main', userMessageRedacted: 'continue' }), {}); });

test('queues next-turn context exactly once when requested', async () => { const queued = []; const hooks = {}; plugin.register({ pluginConfig: { scopes: { agents: ['main'] }, candidateMemories: [{ id: 'state-redacted', kind: 'context', text: 'next section is proof command', relevance: 1 }] }, on: (name, fn) => { hooks[name] = fn; }, enqueueNextTurnInjection: (payload) => queued.push(payload), logger: { warn() {}, debug() {} } }); const result = await hooks.before_prompt_build({ agentId: 'main', userMessageRedacted: 'continue', queueNextTurn: true }); assert.deepEqual(result, {}); assert.equal(queued.length, 1); assert.match(queued[0].context, /Continuation context/); });

test('config normalization forces rawTranscriptUpload false', () => { const config = normalizePluginConfig({ rawTranscriptUpload: true, mode: 'active' }); assert.equal(config.rawTranscriptUpload, false); assert.equal(config.mode, 'active'); });

test('redacted turn builder includes profile agent and session hashes without raw keys', () => { const turn = redactedTurnFromPromptEvent({ ctx: { agentId: 'main', sessionKey: 'session-redacted' }, userMessageRedacted: 'continue' }, normalizePluginConfig({ openclawProfile: 'ExampleProfile' })); assert.equal(turn.summary, 'continue'); assert.equal(turn.agentId, 'main'); assert.equal(turn.openclawProfile, 'ExampleProfile'); assert.match(turn.sessionKeyHash, /^sha256:/); });

test('resolves live plugin config and hook policy when OpenClaw runtime exposes it', () => { const config = resolveOpenClawBrainConfig({ pluginConfig: { mode: 'conservative' }, runtime: { config: { loadConfig: () => ({ plugins: { entries: { openclawbrain: { hooks: { allowPromptInjection: false }, config: { mode: 'proof-only', activationRoot: '/tmp/ocb-live', scopes: { agents: [] } } } } } }) } } }); assert.equal(config.mode, 'proof-only'); assert.equal(config.activationRoot, '/tmp/ocb-live'); assert.deepEqual(config.scopes.agents, []); assert.equal(config.hooks.allowPromptInjection, false); });
