import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { createHash } from 'node:crypto';
import { homedir } from 'node:os';
import path from 'node:path';
const RAW_FIELD_RE = /(^|[_-])(raw[_-]?(messages?|transcripts?|texts?|contents?)|unredacted|private[_-]?text)$/iu;
const SECRET_FIELD_RE = /(^|[_-])(api[_-]?key|access[_-]?token|refresh[_-]?token|authorization|cookie|password|secret|private[_-]?key)$/iu;
const SECRET_VALUE_RE = /(-----BEGIN [A-Z ]*PRIVATE KEY-----|(^|[^A-Za-z0-9])sk-[A-Za-z0-9_-]{12,}|xox[baprs]-[A-Za-z0-9-]{12,}|AKIA[0-9A-Z]{12,}|API_KEY=|PASSWORD=|ACCESS_TOKEN=)/u;
export function defaultActivationRoot(profileId = 'main') { return path.join(homedir(), '.openclawbrain', 'activation', safePathSegment(profileId)); }
export function resolveProofStorePaths(options = {}) { const profileId = options.profileId ?? 'main'; const root = expandHome(options.activationRoot ?? defaultActivationRoot(profileId)); return { profileId, root, proofLog: path.join(root, 'proof-events.jsonl'), statusFile: path.join(root, 'status.json') }; }
export async function appendProofEvent(event, options = {}) { assertSafeProofEvent(event); const paths = resolveProofStorePaths({ ...options, profileId: options.profileId ?? event.profile_id ?? event.profileId ?? 'main' }); await mkdir(paths.root, { recursive: true }); const normalized = normalizeProofEvent(event, paths.profileId); await appendFileAtomic(paths.proofLog, `${JSON.stringify(normalized)}\n`); await writeStatus({ profileId: paths.profileId, enabled: options.enabled ?? true, mode: normalized.runtime_mode ?? options.mode ?? 'conservative', runtimeAdapter: options.runtimeAdapter ?? 'connected', proofEvents: 'writing', rawTranscriptUpload: 'disabled', profileIsolation: 'pass', lastDecision: normalized.decision, lastDecisionAt: normalized.created_at, lastProofEventHash: proofHash(normalized) }, paths); return normalized; }
export async function readProofEvents(options = {}) { const paths = resolveProofStorePaths(options); let text = ''; try { text = await readFile(paths.proofLog, 'utf8'); } catch (error) { if (error.code !== 'ENOENT') throw error; } return text.split('\n').filter(Boolean).map((line) => JSON.parse(line)); }
export async function readStatus(options = {}) { const paths = resolveProofStorePaths(options); try { return JSON.parse(await readFile(paths.statusFile, 'utf8')); } catch (error) { if (error.code !== 'ENOENT') throw error; return { profile_id: paths.profileId, enabled: false, mode: 'conservative', runtime_adapter: 'not-connected', proof_events: 'not-writing', raw_transcript_upload: 'disabled', profile_isolation: 'unknown', last_decision: 'none', last_decision_at: null }; } }
export async function writeStatus(status, pathsOrOptions = {}) { const paths = pathsOrOptions.statusFile ? pathsOrOptions : resolveProofStorePaths(pathsOrOptions); const safeStatus = { schema: 'ocb.status.v1', updated_at: new Date().toISOString(), profile_id: status.profileId ?? status.profile_id ?? paths.profileId, enabled: Boolean(status.enabled), mode: status.mode ?? 'conservative', runtime_adapter: status.runtimeAdapter ?? status.runtime_adapter ?? 'connected', proof_events: status.proofEvents ?? status.proof_events ?? 'writing', raw_transcript_upload: 'disabled', profile_isolation: status.profileIsolation ?? status.profile_isolation ?? 'pass', last_decision: status.lastDecision ?? status.last_decision ?? 'none', last_decision_at: status.lastDecisionAt ?? status.last_decision_at ?? null, last_proof_event_hash: status.lastProofEventHash ?? status.last_proof_event_hash ?? null }; await mkdir(path.dirname(paths.statusFile), { recursive: true }); await writeFile(paths.statusFile, `${JSON.stringify(safeStatus, null, 2)}\n`, 'utf8'); return safeStatus; }
export async function renderStatus(options = {}) { const status = await readStatus(options); return ['OpenClawBrain status', '', `Profile: ${status.profile_id}`, `Enabled: ${status.enabled ? 'yes' : 'no'}`, `Mode: ${status.mode}`, `Runtime adapter: ${status.runtime_adapter}`, `Proof events: ${status.proof_events}`, `Raw transcript upload: ${status.raw_transcript_upload}`, `Profile isolation: ${status.profile_isolation}`, `Last decision: ${status.last_decision}${status.last_decision_at ? `, ${status.last_decision_at}` : ''}`].join('\n'); }
export async function renderProof(options = {}) { const profileId = options.profileId ?? 'main'; const events = await readProofEvents({ ...options, profileId }); const recent = events.slice(-Number(options.limit ?? 25)); const counts = countDecisions(recent); const useful = [...recent].reverse().find((event) => event.decision && event.decision !== 'stay_silent' && event.decision !== 'proof_only') ?? recent.at(-1); const lines = [`OpenClawBrain proof for profile: ${profileId}`, '', `Enabled: ${recent.length > 0 ? 'yes' : 'unknown'}`, `Mode: ${useful?.runtime_mode ?? 'conservative'}`, 'Raw transcript upload: never', `Last ${recent.length ? `${recent.length} decision${recent.length === 1 ? '' : 's'}` : '0 decisions'}:`, ` stay_silent: ${counts.stay_silent}`, ` correction_only: ${counts.correction_only}`, ` full_context: ${counts.full_context}`, ` proof_only: ${counts.proof_only}`]; if (useful) lines.push('', 'Recent useful intervention:', ` Turn type: ${useful.turn_type ?? 'unknown'}`, ` Decision: ${useful.decision ?? useful.kind ?? 'unknown'}`, ` Why: ${useful.reason ?? 'not recorded'}`, ` Raw text stored: ${useful.raw_text_stored ? 'yes' : 'no'}`, ` Redacted proof event: ${useful.redacted_proof_event === false ? 'no' : 'yes'}`); return lines.join('\n'); }
export function assertSafeProofEvent(event) { const issues = []; scanUnsafe(event, [], issues); if (issues.length > 0) { const error = new Error(`unsafe proof event rejected: ${issues.join('; ')}`); error.issues = issues; throw error; } }
function normalizeProofEvent(event, profileId) { return { schema: 'ocb.proof_event.v1', created_at: event.created_at ?? new Date().toISOString(), profile_id: profileId, decision: event.decision ?? event.kind ?? 'stay_silent', runtime_mode: event.runtime_mode ?? event.runtimeMode ?? 'conservative', turn_type: event.turn_type ?? event.turnType ?? 'unknown', reason: event.reason ?? '', raw_text_stored: false, raw_transcript_upload: false, redacted_proof_event: true, selected_memory_ids_redacted: Array.isArray(event.selected_memory_ids_redacted) ? event.selected_memory_ids_redacted.slice(0, 10) : [], policy_version: event.policy_version, turn_id_redacted: event.turn_id_redacted ?? event.turnIdRedacted }; }
function countDecisions(events) { const counts = { stay_silent: 0, correction_only: 0, full_context: 0, proof_only: 0 }; for (const event of events) if (event.decision in counts) counts[event.decision] += 1; return counts; }
async function appendFileAtomic(file, chunk) { let previous = ''; try { previous = await readFile(file, 'utf8'); } catch (error) { if (error.code !== 'ENOENT') throw error; } await writeFile(file, `${previous}${chunk}`, 'utf8'); }
function scanUnsafe(value, pathParts, issues) { if (Array.isArray(value)) return value.forEach((child, index) => scanUnsafe(child, [...pathParts, String(index)], issues)); if (value && typeof value === 'object') { for (const [key, child] of Object.entries(value)) { const nextPath = [...pathParts, key]; if (RAW_FIELD_RE.test(key)) issues.push(`${nextPath.join('.')}: raw/unredacted fields are not allowed`); if (SECRET_FIELD_RE.test(key)) issues.push(`${nextPath.join('.')}: secret-like fields are not allowed`); scanUnsafe(child, nextPath, issues); } return; } if (typeof value === 'string' && SECRET_VALUE_RE.test(value)) issues.push(`${pathParts.join('.') || '<root>'}: secret-like values are not allowed`); }
function proofHash(event) { return `sha256:${createHash('sha256').update(JSON.stringify(event)).digest('hex')}`; }
function expandHome(value) { const text = String(value); return text === '~' ? homedir() : text.startsWith('~/') ? path.join(homedir(), text.slice(2)) : text; }
function safePathSegment(value) { return String(value || 'main').replace(/[^a-zA-Z0-9._-]/g, '-').replace(/^-+|-+$/g, '') || 'main'; }
